version: '3.7'

services:
  postgres-srv:
    image: postgres:alpine
    container_name: postgres-srv
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gfhfpbn0101
      - POSTGRES_DB=scalesdb
    ports:
      - 5432:5432
    networks:
      - identity-network

  identity-api:
    restart: unless-stopped
    image: denis227/scales-identity
    container_name: identity-api
    ports:
      - 5001:80
    #   - 5001:443
    depends_on:
      - postgres-srv
    environment:
      - CONNECTIONSTRINGS__DEFAULT=User ID=postgres;Password=gfhfpbn0101;Host=postgres-srv;Port=5432;Database=scalesdb
      # - ASPNETCORE_URLS=https://+:443;http://+:80
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=secret123
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/www.scalessimmulator.ru_custom_1.pfx
    # volumes:
    #   - ~/.aspnet/https:/https:ro
    networks:
      - identity-network

  # web-srv:
  #   image: nginx:latest
  #   container_name: web-srv
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./nginx-conf:/etc/nginx/conf.d
  #   depends_on:
  #     - identity-api
  #   networks:
  #     - identity-network


networks:
  identity-network:
    driver: bridge